services:
  # Backend - Spring Boot
  app:
    build:
      context: ./backend
    container_name: crud-springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://usuariodobanco:senha@cluster0.datgvgs.mongodb.net/nomedobanco?retryWrites=true&w=majority

    networks:
      - app-network

  # Frontend - Angular com Nginx configurado para redirecionar /api para o backend
  frontend:
    build:
      context: ./frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - app
    networks:
      - app-network

  # Microserviço - Matriculas
  matricula-service:
    build:
      context: ./microservicos/matricula-service
    container_name: matricula-service
    ports:
      - "8081:8081"
    environment:
      - SERVICES_PESSOA_URL=http://pessoa-service:8082/api/pessoas
      - SERVICES_CURSO_URL=http://curso-service:8083/api/cursos
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
