server.port=8081
spring.application.name=matricula-service
spring.datasource.url=jdbc:h2:mem:matriculadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
services.pessoa.url=http://localhost:8082/api/pessoas
services.curso.url=http://localhost:8083/api/cursos
